<?php
// Generated by ZF2's ./bin/classmap_generator.php
return array(
    'Test\Module'                          => __DIR__ . '/Module.php',
    'Test\Controller\IndexController'      => __DIR__ . '/src/Test/Controller/IndexController.php',
    'TestAdmin\Controller\IndexController' => __DIR__ . '/src/TestAdmin/Controller/IndexController.php',
);