<?
/**
 * @var int $page
 * @var array $articles
 * @var Blog\Entity\Article $articles[]
 */
?>

<h1>Blog (archive)</h1>

<? foreach($articles as $article):?>
    <?
    $slug = $this->slug($article->getTitle());
    $url  = $this->url('/article', array(
        'id'    => $article->getId(),
        'title' => $slug
    ));
    ?>

    <article>
        <h2><?= $article->getTitle()?></h2>
        <?= $article->getLead()?>
        
        <p><a href="<?=$url?>">Read more</a></p>
    </article>

<? endforeach?>

<p>
    <a href="<?= $this->url(null, array('page' => $page+1))?>">Older</a>
    <? if($page !== 1):?>
        <a href="<?= $this->url(null, array('page' => $page-1))?>">Newer</a>
    <? endif?>
</p>