<?
/**
 * @var array $articles
 * @var Blog\Entity\Article $articles[]
 */
?>

<h1>Blog</h1>

<? foreach($articles as $article):?>
    <?
    $slug = $this->slug($article->getTitle());
    $url  = $this->url('/article', array(
        'id'    => $article->getId(),
        'title' => $slug
    ));
    ?>

    <article>
        <h2><?= $article->getTitle()?></h2>
        <?= $article->getLead()?>
        
        <p><a href="<?=$url?>">Read more</a></p>
    </article>

<? endforeach?>

<p><a href="<?= $this->url('/archive')?>">More posts in the archive</a></p>