<article>
	<div class="hero-unit">
	    <h1>Welcome to <span class="ensemble">ensemble</span></h1>
	    <p>Congratulations! You have successfully installed the ensemble sample application. The <a href="http://ensemble.github.com">ensemble content management framework</a> is the starting point to develop content management based applications with the Zend Framework 2.</p>
	    <p><a class="btn btn-success btn-large" href="https://github.com/ensemble">Fork ensemble on GitHub &raquo;</a></p>
	</div>

	<div class="row-fluid">
	    <div class="span4">
	        <h2>Follow Development</h2>
	        <p>Zend Framework 2 is under active development. If you are interested in following the development of ZF2, there is a special ZF2 portal on the official Zend Framework webiste which provides links to the ZF2 <a href="http://framework.zend.com/wiki/display/ZFDEV2/Home">wiki</a>, <a href="http://framework.zend.com/zf2/blog">dev blog</a>, <a href="http://framework.zend.com/issues/browse/ZF2">issue tracker</a>, and much more. This is a great resource for staying up to date with the latest developments!</p>
	    </div>

	    <div class="span4">
	        <h2>Discover Modules</h2>
	        <p>The community is working on developing a community site to serve as a repository and gallery for ZF2 modules. The project is available <a href="https://github.com/zendframework/modules.zendframework.com">on GitHub</a>. The site is currently live and currently contains a list of some of the modules already available for ZF2.</p>
	    </div>

	    <div class="span4">
	        <h2>Help &amp; Support</h2>
	        <p>If you need any help or support while developing with ZF2, you may reach us via IRC: <a href="irc://irc.freenode.net/zftalk.2">#zftalk.2 on Freenode</a>. We'd love to hear any questions or feedback you may have regarding the beta releases. Alternatively, you may subscribe and post questions to the <a href="http://framework.zend.com/wiki/display/ZFDEV/Mailing+Lists">mailing lists</a>.</p>
	    </div>
	</div>
</article>