<article>
    <div class="alert alert-info">
        <p>The sitemap in XML format can be downloaded <a href="<?php echo $this->url('sitemap/xml'); ?>">here</a></p>
    </div>

    <?php echo $this->navigation()->menu()
                           ->setMinDepth(null)
                           ->setMaxDepth(null)
                           ->setOnlyActiveBranch(false)
                           ->setRenderInvisible(true); ?>
</article>
